#!/usr/bin/env bash
# A Bash script to transfer a file from client to server

# Check if exactly 4 parameters are provided
if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
file_path="$1"
server_ip="$2"
user="$3"
key_path="$4"

# Transfer the file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$key_path" "$file_path" "$user@$server_ip:~/"

