#!/usr/bin/env bash
# displays a story with each line of /etc/passwd.

file="/etc/passwd"
while IFS=: read -r username passwd uid gid gecos homedir shell
do
    echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell. $uid's place is protected by the passcode $passwd, more info about the user here: $gecos"
done < "$file"
