#!/usr/bin/env bash
# Bash script to display formatted information from /etc/passwd
IFS=":"
while read -r username passwd uid gid gecos homedir shell; do
    echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell. USER ID's place is protected by the passcode $passwd, more info about the user here: $uid"
done < /etc/passwd

