#!/usr/bin/env bash
counter=1
text1="bad luck from China"
text2="bad luck from Japan"
text3="bad luck from Italy"
while [ $counter -le 20 ]; do
	case $counter in
		4)
			echo "$counter"
			echo "$text1"
			((counter++))
			;;
		9)
			echo "$counter"
			echo "$text2"
			((counter++))
			;;
		17)
			echo "$counter"
			echo "$text3"
			((counter++))
			;;
		*)
			echo "$counter"
			((counter++))
			;;
esac
done
