#!/usr/bin/env bash
# Bash script that prints the details of a file

if [[ -e "school" ]]; then
    if [[ -s "school" ]]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    echo "school file exists"

    if [[ -f "school" ]]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi

